CustomRoutes/config/routes.rb
Rails.application.routes.draw do

 	
 	resources :first 




	#get 'first/index' #:to => 'first/fetch_results'
  	#post 'first/create', :to => 'first#create'
	#root 'first#index'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

CustomRoutes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

CustomRoutes/app/models/first.rb
class First < ApplicationRecord
	
end

CustomRoutes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def new
		# @word = params.require(:word).permit(:word)

	end

end

CustomRoutes/app/controllers/first_controller.rb
class FirstController < ApplicationController

	def new
	  	puts "====================> new"
	  	@first = First.new

	end

	def create 
	  	puts "==============================> create"
	   
	    @first = First.create(first_params)  
	end


	def index
	  	puts "=======================================> index"
		@first = First.find(params[:id])
	    
	end

	def show 
		puts "=======================================> show"
		@first = First.find(params[:id])
	   
	end

	def my_data(word)

	  	puts "=========================================> in my_data"
	 	
	 	respond_to do |format|
    		format.js
  		end

	end

	private
		def first_params
	    	params.require(:cr).permit(:word)
	  	end

end


# <%   %>

CustomRoutes/app/helpers/application_helper.rb
module ApplicationHelper
end

CustomRoutes/app/helpers/first_helper.rb
module FirstHelper
end

CustomRoutes/app/views/first/index.html.erb
<h1>Custom Routes</h1>

<%= form_for :cr, remote: true do |w| %>
  	<p>
    	<%= w.label :Enter %>
    	<%= w.text_field :word %>
  	</p>
  	<p>
    	<%= link_to "Search", first_path(@cr), remote: true %>
  	</p>

	<p>
		<%= @cr %>
	</p>
	
<% end %>

<div>
	<p>
		<%= @cr %>
	</p>
</div>

CustomRoutes/app/views/first/show.html.erb
<p>
	<%= @cr %>
</p>

CustomRoutes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomRoutes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>